print('Let\'s poetry! You first:')
animal = input('Name an animal, you little bitch. ')
snack = input('Pick your favorite fucking snack. ')
pokemon = input('Pick a Pokemon, you nerd. ')
print('Cute and chubby')
print('With paws that smell like ' + snack)
print('That\'s my Lucy, super cuddly')
print('Faster than a speeding ' + animal)
print('Stronger than a baby ' + animal)
print('This is Lola, my ' + pokemon )
print('\n')
print('Here\'s mine.')
print('\n')
print('Cute and chubby\nWith paws that smell like Fritos\nThat\'s my Lucy, super cuddly\nFaster than a speeding squirrel\nStronger than a baby ox \n This is Lola, my firefox')

